dist: trusty
language: node_js
node_js:
- '9'
script: npm run build
deploy:
  provider: npm
  email: altay.aydemir@gmail.com
  skip_cleanup: true
  api_key:
    secure: VvYIoxyr2fIRVwPkxmbRdFDxhxtieXpZmroBkwiNZ3xe4DzFaM6PKwEKBZ+LVj7nbyM5KZOD21naPdREUm/HbAUTWU6CPIyltVD85+9vgIZnHYscodc+rS6Jr3+GYrXjuKAr3q8fnOuKIG3gVCiZyqrygmLDZdN9tvlDr7M64On288GY0IId3ZffUOgumuJdkknSEhtsQjj0kmbc3+zJSFEEe/lVvHwEUnaWdmNRLGBHaSoX/wBwojo7zTE6U4EfxcrNr7qrzw4JRIYH5TM3jaUojIRHvTbHp2ALaXzi8IxdHzz2sV9iDU+xlCWMFM/L7E+pU2qBMEvh6M86MC5dxxlTNCmjIRaw8R4DBrNzIkUZ8YakH4/6/lppQcSNT+L/DrDIAVf7PW7fudQfRboVxfKN5v4VpwCZuAnSbrf8dbiisTnyL0cfLgNwyyswuIvA97/NRJpb30vIiLjC/JDweiCNfVXSfGExX78C4qwwCPGKlVVlTrLTo8S2rWEegCKpn5cTNBIdSDYAw+Ic0H5/LF1TVhJv0FBxYRBz+ummzU2sm25HWyuZ8VXymLE9UCbBMLC4GHOxKfN9OFdyNwuDbDmC6+VkRDhlxFatR2FA4JhL/vIzwP+63gr6+Ltx8ZZMTwwnNul5wJiUrNUYdagyhSXN2ayMxXhnlMlFp1IaOFM=
  on:
    tags: true
    repo: aydieneue/putio.js
